PMTS/Models/Photo.cs
namespace PMTS.Models
{
    public class Photo
    {
        public int Id { get; set; }
        public string Name { get; set; } = "notFound.png"; //id + file extension
        public string ThumbName { get; set; } = "notFound.png"; //thumbnail name
        public int ContestantId { get; set; }
        public int TournamentId { get; set; }
        public int BirdN { get; set; } //number of birds in photo
        public int Points { get; set; } //number of points assigned to photo
        public bool BirdDetected { get; set; }
    }
}

PMTS/Models/Tournament.cs
using System.ComponentModel.DataAnnotations;

namespace PMTS.Models
{
    public class Tournament
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Įveskite turnyro pavadinimą.")]
        [StringLength(80, ErrorMessage = "Pavadinimas per ilgas.")]
        [MinLength(3, ErrorMessage = "Pavadinimas per trumpas.")]
        public string Name { get; set; }
        public bool IsPrivate { get; set; }
        public bool RestrictedTypes { get; set; }
        public bool Active { get; set; } = true; //neaktyvus - lyg suarchyvuotas. Kontroliuojamas naudotojo (iki kol turnyras nepasibaigia)
        public bool Ongoing { get; set; } = false; //ar turnyras vyksta (galima jame dalyvauti). Kontroliuojamas sistemos
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public List<Contestant>? Contestants { get; set; }
        public List<Bird>? Birds { get; set; }
        public string? Organizer { get; set; }
        public int UserId { get; set; }
        public int DefaultPoints { get; set; } //kiek tasku verta nuotrauka kai nera rusiu limito

        //public List<Photo> Photos { get; set; }
    }
}

PMTS/Controllers/TournamentsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.IO.Compression;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.IdentityModel.Tokens;
using PMTS.Authentication;
using PMTS.DTOs;
using PMTS.Models;
using static System.Net.Mime.MediaTypeNames;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models;
//using PMTS.Migrations;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection.Metadata;

namespace PMTS.Controllers
{
    public class TournamentsController : Controller
    {
        private readonly PSQLcontext _context;
        private readonly PmtsJwt _pmtsJwt;
        private readonly BlobContainerClient _blobContainerClient;
        //private readonly UsersController _usersController;

        public TournamentsController(PSQLcontext context, PmtsJwt pmtsJwt)
        {
            _context = context;
            _pmtsJwt = pmtsJwt;
            _blobContainerClient = new BlobServiceClient(Environment.GetEnvironmentVariable("Storage")).GetBlobContainerClient("pmts-pic");
            //_usersController = usersController;
        }

        // GET: Tournaments
        public async Task<IActionResult> Index()
        {
            return _context.Tournament != null ?
                        View(await _context.Tournament.Where(t => !t.IsPrivate).ToListAsync()) :
                        Problem("Entity set 'PSQLcontext.Tournament'  is null.");
        }

        public async Task<IActionResult> IndexAdmin()
        {
            try
            {
                string cookie = Request.Cookies["userCookie"];
                JwtSecurityToken validatedToken = _pmtsJwt.Validate(cookie);
                User user = GetUser(int.Parse(validatedToken.Issuer));
                if (user.Admin)
                {
                    return _context.Tournament != null ?
                        View(await _context.Tournament.ToListAsync()) :
                        Problem("Entity set 'PSQLcontext.Tournament'  is null.");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            catch (Exception ex)
            {
                TempData["AuthStatus"] = "AuthError";
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MyTournaments
        public async Task<IActionResult> MyTournaments()
        {
            try
            {
                string cookie = Request.Cookies["userCookie"];
                JwtSecurityToken validatedToken = _pmtsJwt.Validate(cookie);
                User user = GetUser(int.Parse(validatedToken.Issuer));

                MyTournamentsDTO myTournamentsDTO = new MyTournamentsDTO();

                List<Tournament> organizedTournaments = await _context.Tournament.Where(t => t.UserId == user.Id).ToListAsync();
                myTournamentsDTO.organizedTournaments = organizedTournaments;

                List<Contestant> contestants = await _context.Contestant.Where(u => u.UserId == user.Id).ToListAsync();
                foreach (Contestant contestant in contestants)
                    myTournamentsDTO.memberOfTournaments.Add(await _context.Tournament.FirstOrDefaultAsync(t => t.Id == contestant.TournamentId));

                return View(myTournamentsDTO);
            }
            catch (Exception ex)
            {
                TempData["AuthStatus"] = "AuthError";
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Tournaments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            
            if (id == null || _context.Tournament == null)
            {
                return NotFound();
            }

            var tournament = await _context.Tournament
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (tournament == null)
            {
                return NotFound();
            }
            //jei turnyras prasidejo
            if (tournament.Active && tournament.StartTime.ToUniversalTime() < DateTime.Now.ToUniversalTime())
            {
                tournament.Ongoing = true;
            }
            else
                tournament.Ongoing = false;
            //jei turnyras baigesi
            if (tournament.EndTime.ToUniversalTime() < DateTime.Now.ToUniversalTime())
            {
                tournament.Active = false;
                tournament.Ongoing = false;
            }

            _context.Tournament.Update(tournament);
            _context.SaveChanges();

            //Active = true, Ongoing = false - galima prisijungti bet dar negalima kelti nuotrauku
            //Ongoing = true - turnyre galima dalyvauti ir kelti nuotraukas
            //Active = false - turnyre negalima dalyvauti (bagesi arba buvo nutrauktas)

            if(tournament.Active)
            {
                TempData["Active"] = "True";
            }
            if(tournament.Ongoing)
            {
                TempData["Ongoing"] = "True";
            }

            TempData["OrganizerName"] = tournament.Organizer;

            _context.Tournament.Include(tournament => tournament.Contestants).ToList();
            
            try
            {
                if (Request.Cookies["userCookie"] != null)
                {
                    string cookie = Request.Cookies["userCookie"];
                    JwtSecurityToken validatedToken = _pmtsJwt.Validate(cookie);
                    User user = GetUser(int.Parse(validatedToken.Issuer));
                    
                    TempData["LoggedIn"] = "True";
                    if (tournament.UserId == user.Id)
                    {
                        TempData["Organizer"] = "True";
                        TempData["PhotosInList"] = _context.Photo.Where(p => !p.BirdDetected && p.TournamentId == tournament.Id).Count();
                    }
                    else
                    {
                        TempData["Organizer"] = "False";
                    }
                    if (user.Admin)
                    {
                        TempData["IsAdmin"] = "True";
                    }
                    if (!_context.Contestant.IsNullOrEmpty())
                    {
                        var contestant = _context.Contestant.FirstOrDefault(m => m.UserId == user.Id && m.TournamentId == tournament.Id);
                        if (contestant != null)
                        {
                            TempData["IsContestant"] = "True";
                            if (contestant.Removed)
                                TempData["Removed"] = "True";
                        }
                        else
                        {
                            TempData["IsContestant"] = "False";
                        }
                    }
                    else
                    {
                        TempData["IsContestant"] = "False";
                    }
                    if (tournament.IsPrivate)
                    {
                        //jei privatus turnyras, tikrinama ar naudotojas yra dalyvis, rengejas
                        if (!((_context.Contestant.FirstOrDefault(m => m.UserId == user.Id && m.TournamentId == tournament.Id) != null) || tournament.UserId == user.Id || user.Admin))
                        {
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
                else
                {
                    TempData["LoggedIn"] = "False";
                    if (tournament.IsPrivate)
                        return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                //prisijungimas neprivalomas, tad įvykus autentifikacijos nenukreipiama i prisijungima (tik jei privatus)
                TempData["LoggedIn"] = "False";
                if(tournament.IsPrivate)
                    return RedirectToAction("Index", "Home");
            }
            return View(tournament);
        }

        // GET: Tournaments/Create
        public IActionResult Create()
        {
            try
            {
                string cookie = Request.Cookies["userCookie"];
                JwtSecurityToken validatedToken = _pmtsJwt.Validate(cookie);
                User user = GetUser(int.Parse(validatedToken.Issuer));
                if(user == null)
                {
                    TempData["AuthStatus"] = "AuthError";
                    return RedirectToAction("Index", "Home");
                }
                if (user.Admin)
                {
                    return RedirectToAction("Index", "Home");
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["AuthStatus"] = "AuthError";
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Tournaments/ContestantPhotos
        public async Task<IActionResult> ContestantPhotos(int? id)
        {
            if (id == null || _context.Contestant == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestant
                .FirstOrDefaultAsync(m => m.Id == id);

            if (contestant == null)
            {
                return NotFound();
            }

PMTS/Views/Tournaments/AddPhoto.cshtml
@model PMTS.DTOs.PhotoDTO

@{
    ViewData["Title"] = "Nuotraukos įkėlimas";
}

<h4>Įkelkite nuotrauką</h4>
@using (Html.BeginForm("AddPhoto", "Tournaments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
    <input type = "file" asp-for="PhotoData"/>
    </div>
    <div class="form-group">
        <label asp-for="BirdsN" class="control-label"></label>
        <input asp-for="BirdsN" class="form-control" />
        <span asp-validation-for="BirdsN" class="text-danger"></span>
    </div>

    <div>
    <input type="submit" value="Įkelti" class="btn btn-primary" />
    </div>
    <br />
}


@{
    if (TempData["PhotoAdded"] == "True")
    {
        <h4>Nuotrauka pridėta.</h4>
    }
    if (TempData["Error"] == "true")
    {
        <h4>Failas per didelis.</h4>
        <p>Maksimalus failo dydis: 4MB</p>
    }
}

<button onclick="history.back()" class="btn btn-primary">Grįžti</button>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PMTS/Views/Tournaments/AddUserToTournament.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model PMTS.DTOs.AddUserDTO

@{
    ViewData["Title"] = "Naudotojo pridėjimas";
}

<h2>Pridėti naudotoją prie turnyro</h2>

<hr />

@if (TempData["AddStatus"] == "AddSuccess")
{
    <h3>Naudotojas pridėtas</h3>
    <p>Galite pridėti dar vieną naudotoją</p>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUserToTournament">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Naudotojo vardas</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Pridėti" class="btn btn-primary" /> 
            </div>
            <br />
        </form>
    </div>
</div>


@if (TempData["AddStatus"] == "AddFailed")
{
    <h2>Nurodytas naudotojas nerastas</h2>
    <p>Bandykite dar kartą</p>
}
@if (TempData["AddStatus"] == "AlreadyMember")
{
    <h2>Nurodytas naudotojas jau dalyvauja turnyre</h2>
    <p>Bandykite dar kartą</p>
}

<button onclick="history.back()" class="btn btn-primary">Grįžti</button>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

PMTS/Views/Tournaments/CheckPhoto.cshtml
@model IEnumerable<PMTS.Models.Photo>

@{
    ViewData["Title"] = "Nuotraukos";
}

<h2>Nuotraukos rankiniam patikrinimui</h2>

@{
    if (Model.Count() != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nuotrauka
                    </th>
                    <th>
                        Paukščių kiekis nuotraukoje
                    </th>
                    <th>
                        Bendras nuotraukos taškų kiekis
                    </th>
                    <th>
                        
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="Photo" asp-route-id="@item.Id">
                                <img src="https://pmts.blob.core.windows.net/pmts-pic/@item.ThumbName" alt="Nuotrauka Nr. @item.Id" />
                            </a>
                        </td>
                        <td>
                            @item.BirdN
                        </td>
                        <td>
                            @item.Points
                        </td>
                        <td>
                            <a asp-action="ConfirmPhoto" asp-route-id="@item.Id">
                                Patvirtinti
                            </a>
                        </td>
                        <td>
                            <form asp-action="ConfirmPhoto">
                                <input type="hidden" asp-for="@item.Id" />
                                <input type="submit" value="Trinti PLACEHOLDER" class="btn btn-primary" asp-action="ConfirmPhoto" asp-route-id="@item.Id" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h4>Nėra nuotraukų rankiniam patikrinimui</h4>
    }
    @if (TempData["ConfirmStatus"] == "ConfirmFailed")
    {
        <p>nepavyko</p>
    }
    @if (TempData["ConfirmStatus"] == "ConfirmSuccess")
    {
        <p>pavyko</p>
    }
}

PMTS/Views/Tournaments/ContestantPhotos.cshtml
@model PMTS.Models.Contestant

@{
    ViewData["Title"] = "Nuotraukos";
}

<h1>Turnyras @Model.TournamentName</h1>
<h2>Naudotojo @Model.UserName įkeltos nuotraukos</h2>

@{
    if (Model.Photos != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nuotrauka
                    </th>
                    <th>
                        Paukščių kiekis nuotraukoje
                    </th>
                    <th>
                        Bendras nuotraukos taškų kiekis
                    </th>
                    @if (TempData["CanDelete"] == "True")
                    {
                        <th>
                            
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Photos)
                {
                    if(item.BirdDetected)
                    {
                        <tr>
                            <td>
                                <a asp-action="Photo" asp-route-id="@item.Id">
                                    <img src="https://pmts.blob.core.windows.net/pmts-pic/@item.ThumbName" alt="Nuotrauka Nr. @item.Id" />
                                </a>
                            </td>
                            <td>
                                @item.BirdN
                            </td>
                            <td>
                                @item.Points
                            </td>
                            @if(TempData["CanDelete"] == "True")
                            {
                                <td>
                                    <a asp-action="DeleteContestantPhoto" asp-route-id="@item.Id">
                                        Trinti
                                    </a>
                                </td>
                            }
                            
                        </tr>
                    }
                    
                }
            </tbody>
        </table>
    }
    else
    {
        <h3>Nėra įkeltų nuotraukų</h3>
    }
}

PMTS/Views/Tournaments/Create.cshtml
@model PMTS.Models.Tournament

@{
    ViewData["Title"] = "Create";
}

<h1>Naujas turnyras</h1>

<h4>Įveskite turnyro informaciją</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Pavadinimas </label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPrivate" /> Privatus turnyras
                </label>
            </div>
            
            <div class="form-group">
                <label id="PointsLabel" asp-for="DefaultPoints" class="control-label">Vieno paukščio taškų vertė </label>
                <input asp-for="DefaultPoints" class="form-control" />
                <span asp-validation-for="DefaultPoints" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="StartTime" class="control-label">Pradžia </label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label">Pabaiga </label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Pridėti" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Turnyrų sąrašas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PMTS/Views/Tournaments/Delete.cshtml
@model PMTS.Models.Tournament

@{
    ViewData["Title"] = "Turnyro trynimas";
}

<h1>Trinti turnyrą</h1>

<h3>Ar tikrai norite ištrinti šį turnyrą?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Pavadinimas
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Pradžia
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            Pabaiga
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Trinti" class="btn btn-danger" /> |
        <a asp-action="Index">Grįžti</a>
    </form>
</div>

PMTS/Views/Tournaments/Details.cshtml
@model PMTS.Models.Tournament

@{
    ViewData["Title"] = Html.DisplayFor(model => model.Name);
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<div>
    @if(Model.IsPrivate)
    {
        <h4>Privatus turnyras</h4>
    }
    else
    {
        <h4>Viešas turnyras</h4>
    }
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Rengėjas
        </dt>
        <dd class="col-sm-10">
            @TempData["OrganizerName"]
        </dd>
        <dt class = "col-sm-2">
            Pradžia
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            Pabaiga
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt class="col-sm-2">
            Vieno paukščio taškų vertė
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DefaultPoints)
        </dd>
        @if(Model.Active)
        {
            <dt class="col-sm-2">
                Turnyras aktyvus
            </dt>
            @if(Model.Ongoing)
            {
                <dd class="col-sm-10">
                    Turnyras prasidėjęs
                </dd>
            }
            else
            {
                <dd class="col-sm-10">
                    Turnyras dar neprasidėjęs
                </dd>
            }
        }
        else
        {
            <dt class="col-sm-2">
                Turnyras neaktyvus
            </dt>
        }
    </dl>
</div>
<div>
    @{
        if (TempData["LoggedIn"] == "True")
        {
            if (TempData["TournamentError"] == "OwnerJoin")
            {
                <h3>Rengėjas negali prisijungti prie savo turnyro.</h3>
            }
            if (TempData["Organizer"] == "True")
            {
                if (Model.IsPrivate && Model.Active)
                {
                    <a asp-action="AddUserToTournament" asp-route-id="@Model?.Id">Pridėti naudotoją </a>
                    <br />
                }
                <a asp-action="CheckPhoto" asp-route-id="@Model?.Id">Tikrinti nuotraukas (nepatikrintų nuotraukų: @TempData["PhotosInList"]) </a>
                <br />
                <a asp-action="Delete" asp-route-id="@Model?.Id">Trinti</a>
                <br />
                <a asp-action="Edit" asp-route-id="@Model?.Id">Redaguoti </a>
                <br />

            }
            else
            {
                if (TempData["IsContestant"] == "False" && TempData["IsAdmin"] != "True" && TempData["Active"] == "True")
                {
                    <form asp-action="Join">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Prisijungti" class="btn btn-primary" asp-action="Join" asp-route-id="@Model?.Id" />
                    </form>
                }
                if (TempData["IsContestant"] == "True" && TempData["Removed"] != "True")
                {
                    <p>Dalyvaujate šiame turnyre!</p>
                    if (TempData["Ongoing"] == "True")
                    {
                        <input type="hidden" asp-for="Id" />
                        <input type="button" value="Įkelti nuotrauką" class="btn btn-primary" onclick="window.location.href='@Url.Action("AddPhoto", new { Id = Model?.Id })';" />
                        <br />
                    }
                    
                    <a asp-action="LeaveTournament">
                        Išeiti
                    </a>
                }

            }

            if (TempData["IsAdmin"] == "True")
            {
                <a asp-action="Edit" asp-route-id="@Model?.Id">Redaguoti </a>
                <br />
                <a asp-action="Delete" asp-route-id="@Model?.Id">Trinti</a>
                <br />

            }
        }
        
    }
    
    @{
        if (Model.Contestants != null)
        {
            int i = 0;
            var orderedList = Model.Contestants.OrderBy(contestant => contestant.Id).OrderByDescending(contestant => contestant.Points);
            <h4>Dalyviai</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th style="width:2%">
                            #
                        </th>
                        <th>
                            Vardas
                        </th>
                        <th>
                            Taškai
                        </th>
                        @if (TempData["Organizer"] == "True" || TempData["IsAdmin"] == "True")
                        {
                            <th>

                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in orderedList)
                    {
                        if( !item.Removed)
                        {
                            i=i+1;
                            <tr style="height:45px">
                                <td>
                                    @i
                                </td>
                                <td>
                                    <a asp-action="ContestantPhotos" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.UserName)</a>
                                    @if (i == 1)
                                    {
                                        <img src="~/images/gold_medal.png" alt="Auksinis medalis" height="30">
                                    }
                                    @if (i == 2)
                                    {
                                        <img src="~/images/silver_medal.png" alt="Sidabrinis medalis" height="30">
                                    }
                                    @if (i == 3)
                                    {
                                        <img src="~/images/bronze_medal.png" alt="Bronzinis medalis" height="30">
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Points)
                                </td>
                                @if (TempData["Organizer"] == "True" || TempData["IsAdmin"] == "True")
                                {
                                    <td>
                                        <a asp-action="RemoveContestantFromTournament" asp-route-id="@item.Id">
                                            Pašalinti
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    }
    
        
    <a asp-action="Index">Turnyrų sąrašas</a>
</div>

PMTS/Views/Tournaments/Edit.cshtml
@model PMTS.Models.Tournament

@{
    ViewData["Title"] = "Redaguoti turnyrą";
}

<h1>Redaguoti</h1>

<h4>@Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Pavadinimas </label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPrivate" /> Turnyras privatus
                </label>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> Turnyras aktyvus
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Išsaugoti" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Turnyrų sąrašas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PMTS/Views/Tournaments/Index.cshtml
@model IEnumerable<PMTS.Models.Tournament>

@{
    ViewData["Title"] = "Turnyrai";
}

<h1>Vieši turnyrai</h1>

@if (Context.Request.Cookies["userCookie"] != null)
{
    <p>
        <a asp-action="Create">Pridėti</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Pavadinimas
            </th>
            <th>
                Ribojamos rūšys
            </th>
            <th>
                Aktyvus
            </th>
            <th>
                Pradžia
            </th>
            <th>
                Pabaiga
            </th>
            <th>
                Rengėjas
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RestrictedTypes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Organizer)
            </td>
        </tr>
}
    </tbody>
</table>